name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: install
        run: |
          npm ci
      - name: prepare
        run: |
          mkdir dist
          mkdir dist/styleguide
      - name: "eportfolio: build"
        run: |
          cd eportfolio
          npm run build
          cp -R dist/. ../dist/
      - name: "styleguide: build"
        run: |
          cd styleguide
          npm run build
          cp -R catalog/build/. ../dist/styleguide/
      - name: publish
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
          retention-days: 30

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.gh-pages.outputs.page_url }}
    steps:
      - name: deploy to github pages
        id: gh-pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages

  deploy-ftp:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: webseiten.informatik.sg
      url: "http://webseiten.informatik.sg/2022/ina4a/gruppe8/"
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          path: ./
      - name: unarchive artifact
        run: |
          mkdir -p ./upload
          tar -xf artifact.tar -C ./upload
      - name: "ftp: informatik.sg"
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./upload/
